name: MLflow CI Pipeline - Advance

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  train-and-dockerize:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./MLProject

    steps:
    - name: 1. Checkout Repository
      uses: actions/checkout@v4

    - name: 2. Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    - name: 3. Install Dependencies
      run: |
        pip install mlflow==2.19.0 scikit-learn pandas numpy

    - name: 4. Run MLflow Project (Training Model)
      run: |
        mlflow run . --env-manager=local 

    - name: 5. Save Artifacts to GitHub (Memenuhi Syarat Menyimpan Artefak)
      uses: actions/upload-artifact@v4
      with:
        name: trained-model-artifact
        path: ./MLProject/model_dir/ 

    - name: 6. Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 7. Generate Dockerfile & Patch Pip Bug
      run: |
        mlflow models generate-dockerfile -m model_dir -d docker_build_dir
        sed -i 's|https://bootstrap.pypa.io/get-pip.py|https://bootstrap.pypa.io/pip/3.9/get-pip.py|g' docker_build_dir/Dockerfile

    - name: 8. Build and Push Docker Image Manually
      run: |
        cd docker_build_dir
        docker build -t ${{ secrets.DOCKER_USERNAME }}/msml-burnout-model:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/msml-burnout-model:latest